###
GET http://localhost:8000/business/admin/train-station/query-list?page=1&size=2&trainCode=G720
Accept: application/json

###
POST http://localhost:8000/business/admin/train-station/save
Content-Type: application/json


{
   "trainCode": "Gtest",
    "stationIndex": "2",
    "name": "Shanghai",
    "arrival": "19:00:00",
    "departure": "20:00:00",
    "km": "900"
}


###
GET http://localhost:8000/business/admin/train-carriage/query-list?page=1&size=2
Accept: application/json


###
GET http://localhost:8000/business/admin/train-seat/query-list?page=1&size=2
Accept: application/json

###
GET http://localhost:8000/business/admin/train/gen-seat/G66
Accept: application/json


###